// Generated by Dagger (https://dagger.dev).
package com.xdwin.moov.features.home.search;

import com.xdwin.abstraction.dagger.ViewModelFactory;
import dagger.MembersInjector;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class SearchFragment_MembersInjector implements MembersInjector<SearchFragment> {
  private final Provider<ViewModelFactory> viewModelFactoryProvider;

  public SearchFragment_MembersInjector(Provider<ViewModelFactory> viewModelFactoryProvider) {
    this.viewModelFactoryProvider = viewModelFactoryProvider;
  }

  public static MembersInjector<SearchFragment> create(
      Provider<ViewModelFactory> viewModelFactoryProvider) {
    return new SearchFragment_MembersInjector(viewModelFactoryProvider);}

  @Override
  public void injectMembers(SearchFragment instance) {
    injectViewModelFactory(instance, viewModelFactoryProvider.get());
  }

  @InjectedFieldSignature("com.xdwin.moov.features.home.search.SearchFragment.viewModelFactory")
  public static void injectViewModelFactory(SearchFragment instance,
      ViewModelFactory viewModelFactory) {
    instance.viewModelFactory = viewModelFactory;
  }
}
