// Generated by Dagger (https://dagger.dev).
package com.xdwin.moov.features.detail.detail;

import com.xdwin.abstraction.dagger.ViewModelFactory;
import dagger.MembersInjector;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DetailFragment_MembersInjector implements MembersInjector<DetailFragment> {
  private final Provider<ViewModelFactory> modelFactoryProvider;

  public DetailFragment_MembersInjector(Provider<ViewModelFactory> modelFactoryProvider) {
    this.modelFactoryProvider = modelFactoryProvider;
  }

  public static MembersInjector<DetailFragment> create(
      Provider<ViewModelFactory> modelFactoryProvider) {
    return new DetailFragment_MembersInjector(modelFactoryProvider);}

  @Override
  public void injectMembers(DetailFragment instance) {
    injectModelFactory(instance, modelFactoryProvider.get());
  }

  @InjectedFieldSignature("com.xdwin.moov.features.detail.detail.DetailFragment.modelFactory")
  public static void injectModelFactory(DetailFragment instance, ViewModelFactory modelFactory) {
    instance.modelFactory = modelFactory;
  }
}
